<?php

/**
  * Implements hook_menu().
  */
 function menu_magic_menu() {
  $items = array();
  
  $items['demo'] = array(
      'title' => 'A little demo',
      'type' => MENU_NORMAL_ITEM,
      'page callback' => 'demo_basic',
      'access callback' => 'user_access', //user_access('access content')
      'access arguments' => array('access content'),
  );
  $items['magic'] = array(
      'title' => 'A little magic',
      'page callback' => 'menu_magic_basic',
      'access callback' => 'user_access',
      'access arguments' => array('access content'),
  );
  
  $items['magic/%'] = array(
      'title' => 'Even more magical',
      'page callback' => 'menu_magic_extra',
      'page arguments' => array(1),
      'access arguments' => array('access content'),
      'file' => 'menu_magic.extra.inc',
  );
  
  $items['user/%/magic'] = array(
      'title' => 'Magic',
      'description' => 'Magical magic for users',
      'page callback' => 'menu_magic_user_tab',
      'page arguments' => array(1),
      'access callback' => 'user_access',
      'access arguments' => array('administer users'),
      'file' => 'menu_magic_user.inc',
      'type' => MENU_LOCAL_TASK,
  ); 
  // node_load(%)
  $items['node/%node/magic'] = array(
      'title' => 'Magic',
      'description' => 'Do amazing and magical things',
      'page callback' => 'menu_magic_node_context',
      'page arguments' => array(1),
      'access arguments' => array('access content'),
      'file' => 'menu_magic_context.inc',
      'type' => MENU_LOCAL_TASK,
      'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
           
  );
  
  return $items; 
 }
 
  /*
 * My callback funtion. 
 */
function demo_basic() {
    return "<strong>This is a test of demo.</strong>";
}

/*
 * Very simple page element.
 */
function menu_magic_basic() {
    $content = array();
    
    $content['raw_markup'] = array(
        '#type' => 'markup',
        '#markup' => 'Truly, this is magical.',
        '#prefix' => '<p>',
        '#suffix' => '</p>'
    );
    
    $variables = array(
        'path' => 'http://placekitten.com/440/400',
        'alt' => t('This is kitten'),
        'title' => t('This is the title'),
    );
    
    $content['themed_data'] = array(
        '#type' => 'markup',
        '#markup' => theme('image', $variables),
        '#prefix' => '<div class="menu-magic-image">',
        '#suffix' => '</div>',
        '#attached' => array(
            'css' => array(
                drupal_get_path('module', 'menu_magic') . '/menu_magic.css',
            ),
        ),
     );
    
    $content['renderable_element'] = array(
        '#theme' => 'item_list',
        '#title' => t('How do we know it\'s magic?'),
        '#items' => array(
           t("Is is made of wood?"),
           t("Does it sink in water"),
           t("Does it weigh the same as a duck?"), 
           t('The current time is %time.', array('%time' => date('r'))),
        ),
        '#cashe' => array(
            'keys' => array('menu_magic', 'renderable_element'), //menu_magic:renderable_element
            'bin' => 'cache',
            'expire' => time() + 30,
            'granularity' => DRUPAL_CACHE_PER_PAGE,
        ),
    );   
     
    return $content;
}


