<?php

/* 
 * Implements hook_permission().
 */
 function demo_permission() {
     return array(
         'administer demo module' => array(
             'title' => t('Administer demo module.'),
             'description' => t('Perform administration tasks for Demo module.'),
         ),
     );
     
 }
 
/*
 *  Implements hook_node_view().
 *  The below code applies to all nodes.
 */
function demo_node_view($node, $view_mode, $langcode) {
    
     $node->content['demo_field'] = array(
         '#type' => 'markup',
         '#markup' => '<p>' .t('This is a demo.'). '</p>',
         '#weight' => -10,
     );
     
     $node->content['demo_list'] = array(
         '#items' => array('green', 'red', 'white', 'blue'),
         '#theme' => 'item_list',
         '#weight' => -9,
     );
     
     // Must have the Devel module enabled.
     //krumo($node);
 }
