<?php

/* 
 * Implements hook_permission().
 */
 function demo_permission() {
     return array(
         'administer demo module' => array(
             'title' => t('Administer demo module.'),
             'description' => t('Perform administration tasks for Demo module.'),
         ),
     );
     
 }
 
 /*
  * Implements hook_menu().
  */
 function demo_menu() {
  $items = array();
  
  $items['demo'] = array(
      'title' => 'A little demo',
      'type' => MENU_NORMAL_ITEM,
      'page callback' => 'demo_basic',
      'access callback' => 'user_access', //user_access('access content')
      'access arguments' => array('access content'),
  );
  $items['demo2'] = array(
      'title' => 'A little magic',
      'page callback' => 'demo_basic2',
      'access callback' => 'user_access',
      'access arguments' => array('access content'),
  );
  
  $items['demo/%'] = array(
      'title' => 'Even more magical',
      'page callback' => 'demo_magic_extra',
      'page arguments' => array(1),
      'access arguments' => array('access content'),
      'file' => 'demo_magic.extra.inc',
  );
  return $items; 
 }
 
  /*
 * My callback funtion. 
 */
function demo_basic() {
    return "<strong>This is a test of demo.</strong>";
}

/*
 * Very simple page element.
 */
function demo_basic2() {
    $content = array();
    
    $content['raw_markup'] = array(
        '#type' => 'markup',
        '#markup' => '<p>Truly, this is magical.',
        '#prefix' => '<p>',
        '#suffix' => '</p>'
    );
    
    $variables = array(
        'path' => 'http://placekitten.com/440/400',
        'alt' => t('This is kitten'),
        'title' => t('This is the title'),
    );
    
    $content['themed_data'] = array(
        '#type' => 'markup',
        '#markup' => theme('image', $variables),
        '#prefix' => '<div class="menu-magic-image">',
        '#suffix' => '</div>',
        '#attached' => array(
            'css' => array(
                drupal_get_path('module', 'demo') . '/menu_magic.css',
            ),
        ),
     );
    
    $content['renderable_element'] = array(
        '#theme' => 'item_list',
        '#title' => t('How do we know it\'s magic?'),
        '#items' => array(
           t("Is is made of wood?"),
           t("Does it sink in water"),
           t("Does it weigh the same as a duck?"), 
           t('The current time is %time.', array('%time' => date('r'))),
        ),
        '#cashe' => array(
            'keys' => array('menu_magic', 'renderable_element'), //menu_magic:renderable_element
            'bin' => 'cache',
            'expire' => time() + 30,
            'granularity' => DRUPAL_CACHE_PER_PAGE,
        ),
    );   
     
    return $content;
}


/*
 *  Implements hook_node_view().
 */
function demo_node_view($node, $view_mode, $langcode) {
     $node -> content['demo_type'] = array(
         '#type' => 'markup',
         '#markup' => '<p>' .t('This is a demo.'). '</p>',
         '#weight' => -10,
     );
     // This is not working??
     $node->content['demo_list'] = array(
         '#item' => array('green', 'red', 'white', 'blue'),
         '#theme' => 'item_list',
         '#weight' => -9,
     );
     //krumo($node);
 }
