<?php

/**
 * @file
 * This module makes use of the Etsy API, building a storefront for your Etsy items
 *
 * This module adds blocks to display your shop information and featured listings, 
 * as well as individual listing pages based on Etsy listing ID numbers.
 *
 * @author: Joshua Schroeder (jdschroeder) <http://drupal.org/user/202642>
 * @upgrade author: Wendy Perelstein (wperels) <https://drupal.org/user/3241457>
 */

define('ETSY_SHOP_ID', variable_get('etsy_shop_id', ''));

/**
 * Implementation of hook_block().
 * from Drupal 6
 */
//function etsy_shop_block($op = 'list', $delta = 0, $edit = array()) {
//  switch ($op) {
//
//    case 'list':
//      $blocks[0]['info'] = t('Etsy Featured Items');
//      $blocks[1]['info'] = t('Etsy Shop Details');
//      return $blocks;
//
//    case 'view':
//      if ($delta == 0) {
//        $block['subject'] = t('Etsy Featured Items');
//        $block['content'] = etsy_shop_featured_items();
//      }
//      else if ($delta == 1) {
//        $block['subject'] = t('Etsy Shop Details');
//        $block['content'] = etsy_shop_details();
//      }
//
//      return $block;
//  }    
//}

/**
 * Implementation of hook_block().
 */
function etsy_shop_block_info() {
  $blocks = array();
  
  $blocks['featureditems'] = array(
    'info' => t('Etsy Featured Items'),
  );
  $blocks['shopdetails'] = array(
    'info' => t('Etsy Shop Details')
  );
  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function etsy_shop_block_view($delta = '') {
  $block = array();
  
  switch ($delta) {
    case 'featureditems':{
      $block['subject'] = t('Etsy Featured Items');
        $block['content'] = etsy_shop_featured_items();
      break;
    }
    case 'shopdetails':{
      $block['subject'] = t('Etsy Shop Details');
        $block['content'] = etsy_shop_details();
      break;
    }
  }
  return $block;
}

/**
 * Implementation of hook_form_alter().
 */
function etsy_shop_form_alter(&$form, $form_state, $form_id) {
  #krumo($form_id);
  switch ($form_id) {
    case 'etsy_settings_form':
      
      $form['etsy_shop_id'] = array(
        '#type' => 'textfield',
        '#title' => t('Shop ID'),
        '#description' => t('The Etsy shop ID of the store you want to use.'),
        '#default_value' => variable_get('etsy_shop_id', ''),
        '#size' => 40,
        '#maxlength' => 255,
        '#required' => TRUE,
        '#weight' => -9,
        
      );
      #krumo($form);
      #krumo(ETSY_SHOP_ID);
      
      break;
  }
}

/**
 * Implementation of hook_menu().
 */
function etsy_shop_menu() {
  $items = array();
  
  $items['store/items'] = array(
    'title' => t('Listing of Etsy shop items'),
    'description' => t('Listing of Etsy shop items'),
    'page callback' => 'etsy_shop_list_items',
    'access arguments' => array('access content'),
  );
  
  $items['store/listing/%'] = array(
    'title' => t('Item Listing'),
    'description' => t('Full page display for an Etsy listing'),
    'page callback' => 'etsy_shop_listing',
    'access arguments' => array('access content'),
    'page arguments' => array(2),
  );

  return $items;
}

/**
* Implementation of hook_theme().
*/
function etsy_shop_theme() {
  return array(
    'etsy_featured_items_block' => array(
      'template' => 'etsy_featured_items_block',
      'arguments' => array('response' => NULL),
    ),
    'etsy_shop_details_block' => array(
      'template' => 'etsy_shop_details_block',
      'arguments' => array('response' => NULL),
    ),
    
    // TODO: We don't need the entire response. Just theme based on $response->results[0].
    'etsy_listing_page' => array(
      'template' => 'etsy_listing_page',
      'arguments' => array('listing' => NULL),
    ),
  );
}

/**
 * Returns themed shop details block
 */
function etsy_shop_details() {
  $response = etsy_get_object('getShopDetails', array('user_id' => ETSY_SHOP_ID));
  return theme('etsy_shop_details_block', $response);
}

function etsy_shop_list_items() {

  $response = etsy_get_object('getShopListings', array('user_id' => ETSY_SHOP_ID), array('limit' => 100));

  foreach($response->results as $item) {
    $return .= sprintf('<li>%s</li>', l($item->title, $item->url));
  }  
  
  return sprintf("<ol>%s</ol>", $return);
  
}

/**
 * Returns themed featured items block
 */
function etsy_shop_featured_items() {
  $response = etsy_get_object('getFeaturedDetails', array('user_id' => ETSY_SHOP_ID), array('detail_level' => 'high'));
  
  return theme('etsy_featured_items_block', $response);
}

function etsy_shop_listing($listing_id) {
  $listing = etsy_get_object('getListingDetails', array('listing_id' => $listing_id), array('detail_level' => 'high'));
  drupal_set_title($listing->results[0]->title);

  return theme('etsy_listing_page', $listing);
}
